### ISSUE TITLE
Assets: directory already exist and download link is not correct

### ISSUE THREAD

**Issue by AndrewLaptev** [zer0deck/BaldErDash#2]
### Report

Hi!
When checking for the existence of a folder with Assets (line 25), it gives an error that it already exists (it may be worth adding an exception or clarifying the condition). Also a link to download Assets of incorrect format for wget (there are no Assets themselves on the link😁) (line 37)

### System Information
 - Kubuntu 20.04.4
 - Python 3.9.5-3ubuntu0~20.04.1:
     - pkg-resources 0.0.0  
     - pygame        2.1.2  
     - setuptools    44.0.0 
     - wget          3.2    
     - wheel         0.37.1

### Code
https://github.com/zer0deck/BaldErDash/blob/f575091de59a9f2b41899293a84f7e9d601a2f67/src/main.py#L22-L49

**Comment by zer0deck** [comment]
I just haven’t finished it yet and haven’t uploaded it, because I’m still fixing the assets pngs themselves. Everything is in progress. Will be marked when available.

**Comment by zer0deck** [comment]
added assets zip on my web page
